name: Greetings

on: [pull_request, issues]

jobs:
  greeting:pp
    runs-on: ubuntu-latest
    permissions:
      issues: writep
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Message that will be displayed on users first issue'
        pr-message: 'Message that will be displayed on users first pull request'
